apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopssightclient-deployment
  labels:
    app: devopssightclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopssightclient
  template:
    metadata:
      labels:
        app: devopssightclient
    spec:
      containers:
        - name: devopssightclient
          image: devopssightacr.azurecr.io/devopssightclient:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: devopssightAPIUrl
              valueFrom:
                  configMapKeyRef:
                    name: devopssightapi-configmap
                    key: devopssightapi_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: devopssightclient-service
spec:
  type: LoadBalancer
  selector:
    app: devopssightclient
  ports:
    - protocol: TCP
      port: 80