apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: devopssightapi-hpa
spec:
  maxReplicas: 1 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devopssightapi-deployment
  targetCPUUtilizationPercentage: 50 # target CPU utilization
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: devopssightclient-hpa
spec:
  maxReplicas: 1 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devopssightclient-deployment
  targetCPUUtilizationPercentage: 50 # target CPU utilization