apiVersion : apps/v1
kind: Deployment
metadata:
  name: devopssightapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopssightapi
  template:
    metadata:
      labels:
        app: devopssightapi 
    spec:
      containers:
        - name: devopssightapi 
          image: devopssightacr.azurecr.io/devopssightapi
          ports:
          - containerPort: 80