apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopssightapi-deployment
  labels:
    app: devopssightapi
spec:
   replicas: 1
   selector:
      matchLabels:
        app: devopssightapi
   template:
      metadata:
        labels:
          app: devopssightapi
      spec:
        containers:
          - name: devopssightapi
            image: vsesharp/devopssightapi:latest
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 80
            env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: connection_string
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: devopssightapi-service
spec:
  type: NodePort
  selector:
    app: devopssightapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 31000